//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package example;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <group ref="{}andor"/>
 *         <group ref="{}operators"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "and",
    "or",
    "equalto",
    "notequalto"
})
@XmlRootElement(name = "filter")
public class Filter {

    protected And and;
    protected Or or;
    protected Equalto equalto;
    protected Notequalto notequalto;

    /**
     * Gets the value of the and property.
     * 
     * @return
     *     possible object is
     *     {@link And }
     *     
     */
    public And getAnd() {
        return and;
    }

    /**
     * Sets the value of the and property.
     * 
     * @param value
     *     allowed object is
     *     {@link And }
     *     
     */
    public void setAnd(And value) {
        this.and = value;
    }

    /**
     * Gets the value of the or property.
     * 
     * @return
     *     possible object is
     *     {@link Or }
     *     
     */
    public Or getOr() {
        return or;
    }

    /**
     * Sets the value of the or property.
     * 
     * @param value
     *     allowed object is
     *     {@link Or }
     *     
     */
    public void setOr(Or value) {
        this.or = value;
    }

    /**
     * Gets the value of the equalto property.
     * 
     * @return
     *     possible object is
     *     {@link Equalto }
     *     
     */
    public Equalto getEqualto() {
        return equalto;
    }

    /**
     * Sets the value of the equalto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Equalto }
     *     
     */
    public void setEqualto(Equalto value) {
        this.equalto = value;
    }

    /**
     * Gets the value of the notequalto property.
     * 
     * @return
     *     possible object is
     *     {@link Notequalto }
     *     
     */
    public Notequalto getNotequalto() {
        return notequalto;
    }

    /**
     * Sets the value of the notequalto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notequalto }
     *     
     */
    public void setNotequalto(Notequalto value) {
        this.notequalto = value;
    }

}
