//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package example;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Filter }
     * 
     * @return
     *     the new instance of {@link Filter }
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link And }
     * 
     * @return
     *     the new instance of {@link And }
     */
    public And createAnd() {
        return new And();
    }

    /**
     * Create an instance of {@link Or }
     * 
     * @return
     *     the new instance of {@link Or }
     */
    public Or createOr() {
        return new Or();
    }

    /**
     * Create an instance of {@link Equalto }
     * 
     * @return
     *     the new instance of {@link Equalto }
     */
    public Equalto createEqualto() {
        return new Equalto();
    }

    /**
     * Create an instance of {@link Notequalto }
     * 
     * @return
     *     the new instance of {@link Notequalto }
     */
    public Notequalto createNotequalto() {
        return new Notequalto();
    }

}
